name: atmail
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  at_client_mobile: ^3.2.22
  at_onboarding_flutter: ^6.1.12
  flutter_dotenv: ^5.2.1
  path_provider: ^2.1.5
  go_router: ^15.1.3
  flutter_native_splash: ^2.4.4
  flutter_displaymode: ^0.6.0
  shared_preferences: ^2.5.3
  logging: ^1.3.0
  flutter_bloc: ^9.1.1
  uuid: ^3.0.7
  equatable: ^2.0.7
  dart_mappable: ^4.5.0
  intl: ^0.19.0
  rxdart: ^0.28.0
  collection: ^1.19.1
  at_utils: ^3.2.0
  dynamic_color: ^1.7.0
  flex_color_scheme: ^8.2.0
  timeago: ^3.7.1

dev_dependencies:
  build_runner: ^2.4.15
  build_verify: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  go_router_builder: any
  dart_mappable_builder: ^4.5.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
