name: atmail
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  at_client_mobile: ^3.2.22
  at_onboarding_flutter: ^6.1.12
  flutter_dotenv: ^5.2.1
  path_provider: ^2.1.5
  go_router: ^15.1.3
  flutter_native_splash: ^2.4.4
  flutter_displaymode: ^0.6.0
  shared_preferences: ^2.5.3
  logging: ^1.3.0
  flutter_bloc: ^9.1.1
  uuid: ^3.0.7
  equatable: ^2.0.7
  dart_mappable: ^4.5.0
  intl: ^0.19.0
  rxdart: ^0.28.0

dev_dependencies:
  build_runner: ^2.4.15
  build_verify: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  go_router_builder: any
  dart_mappable_builder: ^4.5.0

flutter:
  uses-material-design: true

  assets:
    - .env
